spring:
  datasource:
    url: "jdbc:h2:mem:dockge;DB_CLOSE_DELAY=-1;MODE=PostgreSQL"
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration/h2

server:
  port: 5001

logging:
  level:
    root: INFO
    com.louislam.dockge: DEBUG
    org.flywaydb: DEBUG
