spring:
  datasource:
    url: "jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:dockge}"
    username: ${DB_USER:dockge}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: false

server:
  port: 5001
  compression:
    enabled: true
    min-response-size: 1024

logging:
  level:
    root: INFO
    com.louislam.dockge: INFO
  file:
    name: ./logs/dockge.log
    max-size: 10MB
    max-history: 30
