spring:
  datasource:
    url: "jdbc:sqlite:memory:"
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: false

server:
  port: 5001

logging:
  level:
    root: INFO
    com.louislam.dockge: DEBUG
